# Ligação ao Banco de Dados (marketpalm_db)
spring.datasource.url=jdbc:postgresql://localhost:5432/marketpalm_db
spring.datasource.username=postgres
spring.datasource.password=chagas1406

# Hibernate - Criar as tabelas automaticamente no banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Porta onde o sistema vai correr (padrão 8080)
server.port=8080